### ISSUE TITLE
Blocks on Team page are only clickable on picture, not text.

### ISSUE THREAD

**Issue by emilynevitt** [stats4sd/stats4sd-site#12]
Probably a longer term thing, but it is probably worth adding links to text or an overlay .

**Comment by dave-mills** [comment]
Can probably fix using a Bootstrap [stretched link](https://getbootstrap.com/docs/4.3/utilities/stretched-link/).

**Comment by luciafalcinelli** [comment]
Blocks on Team page are now clickable on picture, name and title of the staff users.
