### ISSUE TITLE
Cannot add user

### ISSUE THREAD

**Issue by emilynevitt** [stats4sd/stats4sd-site#125]
Carlos asked me to make a user account for Claire, but it's giving me an error:

<img width="1172" alt="Screenshot 2019-11-12 at 13 58 36" src="https://user-images.githubusercontent.com/37402972/68677962-e6746180-0554-11ea-9d34-c41276b13684.png">

**Comment by dave-mills** [comment]
Looks like the database was expecting a Freeagent ID and CCRP Task ID for all users - including guests, which will never have these attributes. 

Have fixed the db structure, so we should be able to add guest users again.
