### ISSUE TITLE
Trove upload not working 

### ISSUE THREAD

**Issue by emilynevitt** [stats4sd/stats4sd-site#154]
Possibly to do with uploading for internal only. See image for error.

<img width="1658" alt="Screenshot 2020-04-09 at 13 10 54" src="https://user-images.githubusercontent.com/37402972/78893775-cabdaa80-7a63-11ea-8ea2-e81770070fa0.png">

**Comment by emilynevitt** [comment]
Still not working for me, sorry :(

**Comment by dave-mills** [comment]
Fixed and published to master. Still figuring out the new publishing / pull request process. Should be working in the live site now.
