### ISSUE TITLE
Add quick shortcuts to staff dashboard

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/stats4sd-site#17]
Should include links to: 

 - CCRP Task Tracker
 - Dataset Tracker
 - HRM
 - The read-only dropbox archive

**Comment by luciafalcinelli** [comment]
Included shortcut to Dashboard. I need the HRM's url.

**Comment by dave-mills** [comment]
HRM = hrm.stats4sd.org
Our read-only Dropbox archive: https://www.dropbox.com/sh/lt6aimccb2330nx/AAD6hZ7Beu-FffQsqmLqtE11a?dl=0

**Comment by luciafalcinelli** [comment]
included new reference for hrm and dropbox
