### ISSUE TITLE
CCRP Events need 'from' and 'to' dates, also 'month' if exact date isn't known

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/stats4sd-site#18]
Will need to redo the https://stats4sd.org/ccrp#ccrp-eww page: 

 - remove calendar JS plugin,
 - create view to display all events - with exact dates if known, rough dates if not known.

The event database model should include:
 - start date
 - end date
 - rough dates (text, needed only if start and end dates aren't added).

**Comment by luciafalcinelli** [comment]
removed the calendar JS and included a table for events with date and approximate date. Note: modify the value of default for event_date to null.
