### ISSUE TITLE
Request: sender name in resource review request email to be changed

### ISSUE THREAD

**Issue by emilynevitt** [stats4sd/stats4sd-site#49]
Email shows as being from 'hello=example.com@stats4sd.org
on behalf of Example <hello@example.com>"

Is it possible to make the emails appear more legit-looking by being from something like "hello@stats4sd.org" or similar?  This could be confusing for external reviewers especially.

**Comment by dave-mills** [comment]
The requests now appear to come from the person requesting the review. It still gives the weird `name=stats4sd.org@stats4sd.org` format that I cannot yet figure out...
