### ISSUE TITLE
Add check: tasks completed 

### ISSUE THREAD

**Issue by luciafalcinelli** [stats4sd/stats4sd-site#68]
- [ ] if the activity is marked complete but linked to tasks is not complete give warning to users.

~Automatically create a first timeslip when creating a new task~

 ~prevent deletion of activities for no-admin~

 ~add bookmarks capacity from task tracker 2.0~

~add Freeagent link from task tracker 2.0~

**Comment by dave-mills** [comment]
Each checkbox here is a seperate issue, so I have moved them into seperate issues.
